language: java
jdk:
- oraclejdk7
sudo: false
env:
  global:
  - secure: IfIlF3fkbQiSKD3TFj1pMO4OncjLTrqHSrixP5hKnaGx5wlmL7EXYd/crG04YwM4+qBGzBm+kFNW7IMtHJMGHfgnoQ1Vq4PqvFWBD6exK0czKzg1d8dQi29Kww9B1IrwWOLIEJ2SnzxqMchZnNbRRZZXoauv71Yszzl89YSt0+E=
  - secure: QdjtcJXyI5INw14w8CdOwkhTymf3boRYoyH5BcwS3ZDUe/HbyvDqT8el5kTw2RbqsSDh3X59ITlk0FwSkeXg/4E2yBDJaCl29abBQu7YCwWmW+1wzoT/HI416MmG4wPf26AAGNZkavaE9NEUoxNXsNaC7YJc7aGQTNYsiWfz+kA=
after_success:
- chmod +x ./deploy.sh; ./deploy.sh
